import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, UnderlineType } from 'docx';
import { saveAs } from 'file-saver';
import type { WellnessPlanOutput } from '@/app/schemas/wellness-plan';

/**
 * Generate plain text representation of the wellness plan
 */
export function generatePlainText(result: WellnessPlanOutput): string {
  const { emotionalSupport, wellnessTips, personalizedPlan } = result;
  
  let text = '';
  
  // Title
  text += `${personalizedPlan.title.toUpperCase()}\n`;
  text += `${'='.repeat(personalizedPlan.title.length)}\n\n`;
  
  // Plan Details
  text += `Effort Level: ${personalizedPlan.estimatedEffort}\n`;
  text += `Timeframe: ${personalizedPlan.timeframe}\n\n`;
  
  // Emotional Support
  text += `EMOTIONAL SUPPORT\n`;
  text += `-`.repeat(20) + `\n`;
  text += `${emotionalSupport}\n\n`;
  
  // Overview
  text += `OVERVIEW\n`;
  text += `-`.repeat(20) + `\n`;
  text += `${personalizedPlan.overview}\n\n`;
  
  // Key Actions
  if (personalizedPlan.summaryBullets && personalizedPlan.summaryBullets.length > 0) {
    text += `KEY ACTIONS\n`;
    text += `-`.repeat(20) + `\n`;
    personalizedPlan.summaryBullets.forEach((bullet, idx) => {
      text += `${idx + 1}. ${bullet}\n`;
    });
    text += `\n`;
  }
  
  // Action Steps
  text += `ACTION STEPS (${personalizedPlan.steps.length})\n`;
  text += `-`.repeat(20) + `\n`;
  personalizedPlan.steps.forEach((step, idx) => {
    text += `\n${idx + 1}. ${step.text}\n`;
    text += `   Category: ${step.category}`;
    if (step.priority) text += ` | Priority: ${step.priority}`;
    if (step.durationMinutes) text += ` | Duration: ${step.durationMinutes} min`;
    if (step.frequency) text += ` | Frequency: ${step.frequency}`;
    if (step.when) text += ` | When: ${step.when}`;
    text += `\n`;
    if (step.safety) text += `   ⚠️  Safety: ${step.safety}\n`;
    if (step.followUpQuestion) text += `   💭 Reflect: ${step.followUpQuestion}\n`;
  });
  
  // Wellness Tips
  text += `\nADDITIONAL WELLNESS TIPS\n`;
  text += `-`.repeat(20) + `\n`;
  text += `${wellnessTips}\n\n`;
  
  // Footer
  text += `\n${'='.repeat(50)}\n`;
  text += `Generated by DAMII: Your Wellness Assistant\n`;
  text += `Date: ${new Date().toLocaleDateString()}\n`;
  
  return text;
}

/**
 * Copy plain text to clipboard
 */
export async function copyToClipboard(result: WellnessPlanOutput): Promise<void> {
  const text = generatePlainText(result);
  await navigator.clipboard.writeText(text);
}

/**
 * Export wellness plan as PDF
 */
export function exportToPDF(result: WellnessPlanOutput, fileName?: string): void {
  const { emotionalSupport, wellnessTips, personalizedPlan } = result;
  
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - 2 * margin;
  let yPosition = 20;
  
  // Helper to add text with word wrap
  const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
    doc.setFontSize(fontSize);
    doc.setFont('helvetica', isBold ? 'bold' : 'normal');
    doc.setTextColor(color[0], color[1], color[2]);
    
    const lines = doc.splitTextToSize(text, maxWidth);
    lines.forEach((line: string) => {
      if (yPosition > 280) {
        doc.addPage();
        yPosition = 20;
      }
      doc.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
  };
  
  const addSpace = (space: number = 5) => {
    yPosition += space;
  };
  
  // Title
  addText(personalizedPlan.title.toUpperCase(), 18, true, [41, 128, 185]);
  addSpace(8);
  
  // Plan Details
  addText(`Effort: ${personalizedPlan.estimatedEffort.toUpperCase()} | Timeframe: ${personalizedPlan.timeframe}`, 10, false, [100, 100, 100]);
  addSpace(10);
  
  // Emotional Support
  addText('EMOTIONAL SUPPORT', 14, true);
  addSpace(3);
  addText(emotionalSupport, 11);
  addSpace(10);
  
  // Overview
  addText('OVERVIEW', 14, true);
  addSpace(3);
  addText(personalizedPlan.overview, 11);
  addSpace(10);
  
  // Key Actions
  if (personalizedPlan.summaryBullets && personalizedPlan.summaryBullets.length > 0) {
    addText('KEY ACTIONS', 14, true);
    addSpace(3);
    personalizedPlan.summaryBullets.forEach((bullet, idx) => {
      addText(`${idx + 1}. ${bullet}`, 11);
      addSpace(2);
    });
    addSpace(8);
  }
  
  // Action Steps
  addText(`ACTION STEPS (${personalizedPlan.steps.length})`, 14, true);
  addSpace(5);
  
  personalizedPlan.steps.forEach((step, idx) => {
    // Step number and text
    addText(`${idx + 1}. ${step.text}`, 11, true);
    addSpace(2);
    
    // Metadata
    let metadata = `Category: ${step.category}`;
    if (step.priority) metadata += ` | Priority: ${step.priority}`;
    if (step.durationMinutes) metadata += ` | ${step.durationMinutes} min`;
    if (step.frequency) metadata += ` | ${step.frequency}`;
    if (step.when) metadata += ` | ${step.when}`;
    
    addText(metadata, 9, false, [100, 100, 100]);
    addSpace(2);
    
    if (step.safety) {
      addText(`⚠️  Safety: ${step.safety}`, 9, false, [200, 100, 0]);
      addSpace(2);
    }
    
    if (step.followUpQuestion) {
      addText(`💭 ${step.followUpQuestion}`, 9, false, [100, 100, 150]);
      addSpace(2);
    }
    
    addSpace(5);
  });
  
  // Additional Tips
  addText('ADDITIONAL WELLNESS TIPS', 14, true);
  addSpace(3);
  addText(wellnessTips, 11);
  addSpace(10);
  
  // Footer
  addText('Generated by DAMII: Your Wellness Assistant', 9, false, [150, 150, 150]);
  addText(`Date: ${new Date().toLocaleDateString()}`, 9, false, [150, 150, 150]);
  
  // Save
  const defaultFileName = `${personalizedPlan.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.pdf`;
  doc.save(fileName || defaultFileName);
}

/**
 * Export wellness plan as DOCX
 */
export async function exportToDOCX(result: WellnessPlanOutput, fileName?: string): Promise<void> {
  const { emotionalSupport, wellnessTips, personalizedPlan } = result;
  
  const children: Paragraph[] = [];
  
  // Title
  children.push(
    new Paragraph({
      text: personalizedPlan.title.toUpperCase(),
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 },
    })
  );
  
  // Plan Details
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Effort: ${personalizedPlan.estimatedEffort.toUpperCase()} | Timeframe: ${personalizedPlan.timeframe}`,
          color: '808080',
          size: 20,
        }),
      ],
      alignment: AlignmentType.CENTER,
      spacing: { after: 300 },
    })
  );
  
  // Emotional Support
  children.push(
    new Paragraph({
      text: 'EMOTIONAL SUPPORT',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    })
  );
  
  children.push(
    new Paragraph({
      text: emotionalSupport,
      spacing: { after: 300 },
    })
  );
  
  // Overview
  children.push(
    new Paragraph({
      text: 'OVERVIEW',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    })
  );
  
  children.push(
    new Paragraph({
      text: personalizedPlan.overview,
      spacing: { after: 300 },
    })
  );
  
  // Key Actions
  if (personalizedPlan.summaryBullets && personalizedPlan.summaryBullets.length > 0) {
    children.push(
      new Paragraph({
        text: 'KEY ACTIONS',
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 100 },
      })
    );
    
    personalizedPlan.summaryBullets.forEach((bullet, idx) => {
      children.push(
        new Paragraph({
          text: `${idx + 1}. ${bullet}`,
          spacing: { after: 100 },
          numbering: {
            reference: 'my-numbering',
            level: 0,
          },
        })
      );
    });
    
    children.push(new Paragraph({ text: '', spacing: { after: 200 } }));
  }
  
  // Action Steps
  children.push(
    new Paragraph({
      text: `ACTION STEPS (${personalizedPlan.steps.length})`,
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 200, after: 100 },
    })
  );
  
  personalizedPlan.steps.forEach((step, idx) => {
    // Step title
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: `${idx + 1}. ${step.text}`,
            bold: true,
          }),
        ],
        spacing: { before: 150, after: 50 },
      })
    );
    
    // Metadata
    let metadata = `Category: ${step.category}`;
    if (step.priority) metadata += ` | Priority: ${step.priority}`;
    if (step.durationMinutes) metadata += ` | Duration: ${step.durationMinutes} min`;
    if (step.frequency) metadata += ` | Frequency: ${step.frequency}`;
    if (step.when) metadata += ` | When: ${step.when}`;
    
    children.push(
      new Paragraph({
        children: [
          new TextRun({
            text: metadata,
            color: '808080',
            size: 18,
          }),
        ],
        spacing: { after: 50 },
      })
    );
    
    if (step.safety) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `⚠️  Safety: ${step.safety}`,
              color: 'FF6600',
              size: 18,
            }),
          ],
          spacing: { after: 50 },
        })
      );
    }
    
    if (step.followUpQuestion) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `💭 ${step.followUpQuestion}`,
              color: '6666AA',
              size: 18,
              italics: true,
            }),
          ],
          spacing: { after: 100 },
        })
      );
    }
  });
  
  // Additional Tips
  children.push(
    new Paragraph({
      text: 'ADDITIONAL WELLNESS TIPS',
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 300, after: 100 },
    })
  );
  
  children.push(
    new Paragraph({
      text: wellnessTips,
      spacing: { after: 300 },
    })
  );
  
  // Footer
  children.push(
    new Paragraph({
      text: '',
      spacing: { before: 400 },
    })
  );
  
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by DAMII: Your Wellness Assistant',
          color: '999999',
          size: 18,
        }),
      ],
    })
  );
  
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `Date: ${new Date().toLocaleDateString()}`,
          color: '999999',
          size: 18,
        }),
      ],
    })
  );
  
  const doc = new Document({
    sections: [
      {
        properties: {},
        children,
      },
    ],
    numbering: {
      config: [
        {
          reference: 'my-numbering',
          levels: [
            {
              level: 0,
              format: 'decimal',
              text: '%1.',
              alignment: AlignmentType.LEFT,
            },
          ],
        },
      ],
    },
  });
  
  const blob = await Packer.toBlob(doc);
  const defaultFileName = `${personalizedPlan.title.replace(/[^a-z0-9]/gi, '-').toLowerCase()}.docx`;
  saveAs(blob, fileName || defaultFileName);
}
